### PR TITLE
SB-29856 | Fix for hierarchy update API

### PR DESCRIPTION
**Pull request by karthik-tarento**

### CODE REVIEW

**Comment by karthik-tarento** [comment]
@vinukumar-vs @Jayaprakash8887 
PR for discussion - https://github.com/project-sunbird/sunbird-community/discussions/793
Please review and provide your comment

**Comment by vinukumar-vs** [comment]
@pkranga @karthik-tarento We will merge this PR as part of release-4.10. Current 4.9 is already in preprod.

**Comment by karthik-tarento** [comment]
@vinukumar-vs any update on this PR ?

**Comment by vinukumar-vs** [comment]
@karthik-tarento Can you re-create the PR by pointing to release-4.10.0.

**Comment by vinukumar-vs** [comment]
@karthik-tarento Can you re-create the PR by pointing to release-4.10.0.

**Review by vinukumar-vs — APPROVED** [review]

**Pull request merged**
